name = "MCMCChainsStorage"
uuid = "51a256e2-afd8-4c38-88d8-a98ba8ad53ca"
authors = ["Will M. Farr <wfarr@flatironinstitute.org>"]
version = "0.1.2"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
HDF5 = "0.16"
MCMCChains = "4, 5, 6"
